# Generated by Django 5.2.1 on 2025-06-06 13:03

from django.db import migrations
# from profiles.models import Profile, User


# def replace_profile(apps, schema_editor):
#     old_profiles_model = apps.get_model("oc_lettings_site", "Profile")
#
#     for old_profile in old_profiles_model.objects.all():
#         user = User.objects.get(pk=old_profile.user.pk)
#         profile = Profile(user=user, favorite_city=old_profile.favorite_city)
#         profile.save()



class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    # ajouter l'opération (utiliser runpython → se documenter)
    # créer migration vide et utiliser runpython pour récupérer les anciens modèles et itérer
    # dessus afi nde créer les nouveaux modèles à push dans la nouvelle base de données.
    operations = [
        # migrations.RunPython(replace_profile)
    ]
