# Generated by Django 5.2.1 on 2025-06-06 13:03

from django.db import migrations
from profiles.models import Profile, User


def replace_profile(apps, schema_editor):
    """
         Migrate the Profiles' objects of the oc_lettings_site into similar objects
         belonging to the profiles app.
        """
    old_profiles_model = apps.get_model("oc_lettings_site", "Profile")

    for old_profile in old_profiles_model.objects.all():
        user = User.objects.get(pk=old_profile.user.pk)
        profile = Profile(user=user, favorite_city=old_profile.favorite_city)
        profile.save()


class Migration(migrations.Migration):
    """
        Migrate database's objects created using the oc_lettings_site's models
        into objects based on the lettings models
        """
    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_profile)
    ]
