# Generated by Django 5.2.1 on 2025-06-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    # ajouter l'opération (utiliser runpython -> se documenter)
    # créer migration vide et utiliser runpython pour récupérer les anciens modèles et itérer
    # dessus afi nde créer les nouveaux modèles à push dans la nouvelle base de données.
    operations = [
    ]
