# Generated by Django 5.2.1 on 2025-06-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
    ]
