# Generated by Django 5.2.1 on 2025-06-06 13:36

from django.db import migrations
from oc_lettings_site.models import Letting as OldLetting
from oc_lettings_site.models import Address as OldAddress
from lettings.models import Letting, Address


def replace_models(apps, schema_editor):
    old_letting_model = apps.get_model("oc_lettings_site", "Letting")

    for old_letting in old_letting_model.objects.all():
        address = Address(number=old_letting.address.number, street=old_letting.address.street,
                          city=old_letting.address.city, state=old_letting.address.state,
                          zip_code=old_letting.address.zip_code, country_iso_code=old_letting.address.country_iso_code)
        address.save()
        letting = Letting(title=old_letting.title, address=address)
        letting.save()


class Migration(migrations.Migration):
    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_models)
    ]
