# Generated by Django 5.2.1 on 2025-06-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
    ]
