# Generated by Django 5.2.1 on 2025-06-13 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ("profiles", "0002_auto_20250606_1303"),
        ("lettings", "0002_auto_20250606_1336"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
